"""Generate valid .ipynb Jupyter notebook files."""

import json

import nbformat
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook


def generate_notebook(original_code: str, refactored_code: str) -> str:
    """Generate a Jupyter notebook with the migration.

    The notebook contains:
    1. A markdown cell explaining the migration
    2. A pip install cell for ttnn
    3. A code cell with the original PyTorch code
    4. A code cell with the refactored ttnn code

    Args:
        original_code: The original PyTorch source code.
        refactored_code: The refactored ttnn code.

    Returns:
        The notebook JSON as a string.
    """
    nb = new_notebook()
    nb.metadata.kernelspec = {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3",
    }

    # Markdown explanation cell
    nb.cells.append(
        new_markdown_cell(
            "# PyTorch to ttnn Migration\n\n"
            "This notebook was generated by **TT-Migrate**.\n\n"
            "It contains the original PyTorch code and the migrated ttnn version "
            "for Tenstorrent hardware.\n\n"
            "## Steps\n"
            "1. Install dependencies\n"
            "2. Review original PyTorch code\n"
            "3. Review and run the migrated ttnn code"
        )
    )

    # Pip install cell
    nb.cells.append(
        new_code_cell(
            "# Install Tenstorrent ttnn (adjust version as needed)\n"
            "# !pip install tt-metal\n"
            "# !pip install torch  # For reference/comparison"
        )
    )

    # Original code cell
    nb.cells.append(
        new_markdown_cell("## Original PyTorch Code")
    )
    nb.cells.append(new_code_cell(original_code.strip()))

    # Refactored code cell
    nb.cells.append(
        new_markdown_cell("## Migrated ttnn Code")
    )
    nb.cells.append(new_code_cell(refactored_code.strip()))

    return json.dumps(nbformat.from_dict(nb), indent=2)
